[metadata]
name = dreams
description = Distribution System Energy Analysis and Mapping Suite
author = Thad Haines
author_email = jthaine@sandia.gov
version = 1.1.1

[options]
install_requires =
    dss-python
    geopandas
    ipympl
    ipython
    numpy==1.23.3
    matplotlib==3.7.3
    OpenDSSDirect.py[extras]==0.8.4
    openpyxl
    scipy
    seaborn
    Shapely
    simplekml
    XlsxWriter
    contextily==1.2.0
    cmasher
    plotly
    nbformat
    wxpython
    xarray
    mapclassify
    nbformat
    ipykernel